"""empty message

Revision ID: 0a57b056fedc
Revises: dd67d2df8bc8
Create Date: 2025-11-28 19:54:30.409663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a57b056fedc'
down_revision = 'dd67d2df8bc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_administrator',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('adminname', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('rdatetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('adminname'),
    sa.UniqueConstraint('phone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_administrator')
    # ### end Alembic commands ###
