"""empty message

Revision ID: 29811b201966
Revises: 83ec01ae1a9a
Create Date: 2025-12-10 16:08:52.697853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29811b201966'
down_revision = '83ec01ae1a9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='订单主键ID'),
    sa.Column('order_no', sa.String(length=32), nullable=False, comment='订单编号'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('goods_id', sa.Integer(), nullable=False, comment='商品ID'),
    sa.Column('merchant_id', sa.Integer(), nullable=False, comment='商户ID'),
    sa.Column('address_id', sa.Integer(), nullable=True, comment='收货地址ID'),
    sa.Column('point_amount', sa.Float(precision=10, asdecimal=2), nullable=False, comment='消耗积分数量'),
    sa.Column('order_status', sa.SmallInteger(), nullable=False, comment='订单状态：0-创建中 1-已扣积分 2-商户已接单 3-已发货 4-完成 5-取消 6-售后中'),
    sa.Column('logistics_no', sa.String(length=64), nullable=True, comment='物流单号'),
    sa.Column('logistics_company', sa.String(length=32), nullable=True, comment='物流公司名称'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('pay_time', sa.DateTime(), nullable=True, comment='积分扣除成功时间'),
    sa.Column('ship_time', sa.DateTime(), nullable=True, comment='商户发货时间'),
    sa.Column('finish_time', sa.DateTime(), nullable=True, comment='订单完成时间'),
    sa.Column('cancel_time', sa.DateTime(), nullable=True, comment='订单取消时间'),
    sa.Column('cancel_reason', sa.String(length=100), nullable=True, comment='取消原因'),
    sa.Column('remark', sa.String(length=200), nullable=True, comment='订单备注'),
    sa.Column('is_delete', sa.SmallInteger(), nullable=False, comment='软删除标识'),
    sa.ForeignKeyConstraint(['address_id'], ['tb_address.id'], ),
    sa.ForeignKeyConstraint(['goods_id'], ['tb_goods.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['tb_merchant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tb_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_order')
    # ### end Alembic commands ###
