"""empty message

Revision ID: 2c257c8f3d8e
Revises: 66f685ce91fa
Create Date: 2025-12-07 12:55:13.738535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c257c8f3d8e'
down_revision = '66f685ce91fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_address', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
