"""empty message

Revision ID: 306ec3560023
Revises: 7331f4ed2c61
Create Date: 2025-11-21 17:13:20.691059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '306ec3560023'
down_revision = '7331f4ed2c61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=30), nullable=False))
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
