"""add_sms_code_table

Revision ID: 5d691ebaa762
Revises: 90d2c88ee6d5
Create Date: 2025-12-19 11:36:39.134465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d691ebaa762'
down_revision = '90d2c88ee6d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_sms_code',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=False, comment='手机号'),
    sa.Column('code', sa.String(length=6), nullable=False, comment='验证码'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('expire_time', sa.DateTime(), nullable=False, comment='过期时间'),
    sa.Column('is_used', sa.Boolean(), nullable=True, comment='是否已使用：True-已使用，False-未使用'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tb_sms_code', schema=None) as batch_op:
        batch_op.create_index('idx_phone_used', ['phone', 'is_used'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_sms_code', schema=None) as batch_op:
        batch_op.drop_index('idx_phone_used')

    op.drop_table('tb_sms_code')
    # ### end Alembic commands ###
