"""empty message

Revision ID: 5d7f008d15c0
Revises: 2c257c8f3d8e
Create Date: 2025-12-07 13:12:34.039791

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d7f008d15c0'
down_revision = '2c257c8f3d8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_address', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
