"""empty message

Revision ID: 66f685ce91fa
Revises: 69d8153271c1
Create Date: 2025-12-06 21:47:02.105567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66f685ce91fa'
down_revision = '69d8153271c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_address',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('detail', sa.String(length=200), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['tb_user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_address')
    # ### end Alembic commands ###
