"""empty message

Revision ID: 69d8153271c1
Revises: 0a57b056fedc
Create Date: 2025-12-06 19:15:25.511866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69d8153271c1'
down_revision = '0a57b056fedc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('points', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_user', schema=None) as batch_op:
        batch_op.drop_column('points')
        batch_op.drop_column('nickname')

    # ### end Alembic commands ###
