"""empty message

Revision ID: 83ec01ae1a9a
Revises: dcd5d048e922
Create Date: 2025-12-09 20:26:03.772976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83ec01ae1a9a'
down_revision = 'dcd5d048e922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_point_rule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='规则ID'),
    sa.Column('trip_mode', sa.String(length=30), nullable=False, comment='出行方式（walk/bike/public_transit/car）'),
    sa.Column('carbon_reduction_coeff', sa.Float(), nullable=False, comment='碳减排系数（kg CO₂/公里）'),
    sa.Column('point_exchange_coeff', sa.Float(), nullable=False, comment='积分兑换系数（积分/kg CO₂）'),
    sa.Column('remark', sa.String(length=100), nullable=True, comment='规则备注（如：步行每公里减排0.09kg CO₂，1kg兑换10积分）'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_mode')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_point_rule')
    # ### end Alembic commands ###
