"""empty message

Revision ID: bdfab6da94c4
Revises: e7651cdb7b29
Create Date: 2025-12-11 11:34:23.776135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdfab6da94c4'
down_revision = 'e7651cdb7b29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_goods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='商品ID（主键）'),
    sa.Column('merchant_username', sa.String(length=30), nullable=False, comment='商户ID'),
    sa.Column('goods_name', sa.String(length=100), nullable=False, comment='商品名称（如：环保水杯、帆布包）'),
    sa.Column('description', sa.Text(), nullable=True, comment='商品详细描述（可选）'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='商品分类（如：日用品、文创、数码）'),
    sa.Column('need_points', sa.Float(), nullable=False, comment='兑换该商品所需积分（如：100、250.5）'),
    sa.Column('stock', sa.Integer(), nullable=False, comment='商品库存数量（≥0）'),
    sa.Column('stock_warning', sa.Integer(), nullable=True, comment='库存预警值（低于该值提醒补货）'),
    sa.Column('img_url', sa.String(length=255), nullable=True, comment='商品图片URL（存储静态文件路径，如：/static/img/goods/1.jpg）'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='商品状态：on_shelf/off_shelf/sold_out'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='（上架时间）'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='商品信息更新时间'),
    sa.ForeignKeyConstraint(['merchant_username'], ['tb_merchant.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='订单主键ID'),
    sa.Column('order_no', sa.String(length=32), nullable=False, comment='订单编号'),
    sa.Column('user_username', sa.String(length=30), nullable=False, comment='用户ID'),
    sa.Column('goods_id', sa.Integer(), nullable=False, comment='商品ID'),
    sa.Column('merchant_username', sa.String(length=30), nullable=False, comment='商户ID'),
    sa.Column('address_id', sa.Integer(), nullable=True, comment='收货地址ID'),
    sa.Column('point_amount', sa.Float(precision=10, asdecimal=2), nullable=False, comment='消耗积分数量'),
    sa.Column('order_status', sa.SmallInteger(), nullable=False, comment='订单状态：0-创建中 1-已扣积分 2-商户已接单 3-已发货 4-完成 5-取消 6-售后中'),
    sa.Column('logistics_no', sa.String(length=64), nullable=True, comment='物流单号'),
    sa.Column('logistics_company', sa.String(length=32), nullable=True, comment='物流公司名称'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('pay_time', sa.DateTime(), nullable=True, comment='积分扣除成功时间'),
    sa.Column('ship_time', sa.DateTime(), nullable=True, comment='商户发货时间'),
    sa.Column('finish_time', sa.DateTime(), nullable=True, comment='订单完成时间'),
    sa.Column('cancel_time', sa.DateTime(), nullable=True, comment='订单取消时间'),
    sa.Column('cancel_reason', sa.String(length=100), nullable=True, comment='取消原因'),
    sa.Column('remark', sa.String(length=200), nullable=True, comment='订单备注'),
    sa.Column('is_delete', sa.SmallInteger(), nullable=False, comment='软删除标识'),
    sa.ForeignKeyConstraint(['address_id'], ['tb_address.id'], ),
    sa.ForeignKeyConstraint(['goods_id'], ['tb_goods.id'], ),
    sa.ForeignKeyConstraint(['merchant_username'], ['tb_merchant.username'], ),
    sa.ForeignKeyConstraint(['user_username'], ['tb_user.username'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_order')
    op.drop_table('tb_goods')
    # ### end Alembic commands ###
