"""empty message

Revision ID: dcd5d048e922
Revises: e3cfd199bf0c
Create Date: 2025-12-09 20:09:14.652148

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dcd5d048e922'
down_revision = 'e3cfd199bf0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_goods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='商品ID（主键）'),
    sa.Column('goods_name', sa.String(length=100), nullable=False, comment='商品名称（如：环保水杯、帆布包）'),
    sa.Column('description', sa.Text(), nullable=True, comment='商品详细描述（可选）'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='商品分类（如：日用品、文创、数码）'),
    sa.Column('need_points', sa.Float(), nullable=False, comment='兑换该商品所需积分（如：100、250.5）'),
    sa.Column('stock', sa.Integer(), nullable=False, comment='商品库存数量（≥0）'),
    sa.Column('stock_warning', sa.Integer(), nullable=True, comment='库存预警值（低于该值提醒补货）'),
    sa.Column('img_url', sa.String(length=255), nullable=True, comment='商品图片URL（存储静态文件路径，如：/static/img/goods/1.jpg）'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='商品状态：on_shelf/off_shelf/sold_out'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='（上架时间）'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='商品信息更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tb_usertrip', schema=None) as batch_op:
        batch_op.alter_column('period',
               existing_type=mysql.VARCHAR(length=50),
               comment='出行周期（如：2025-11-01 - 2025-11-07）',
               existing_comment='出行周期（如：2025-11-01 ~ 2025-11-07）',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_usertrip', schema=None) as batch_op:
        batch_op.alter_column('period',
               existing_type=mysql.VARCHAR(length=50),
               comment='出行周期（如：2025-11-01 ~ 2025-11-07）',
               existing_comment='出行周期（如：2025-11-01 - 2025-11-07）',
               existing_nullable=False)

    op.drop_table('tb_goods')
    # ### end Alembic commands ###
