"""empty message

Revision ID: e3cfd199bf0c
Revises: b3e21ce7e48c
Create Date: 2025-12-07 21:25:46.541216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3cfd199bf0c'
down_revision = 'b3e21ce7e48c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_usertrip',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='出行记录ID'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='关联用户名（外键）'),
    sa.Column('period', sa.String(length=50), nullable=False, comment='出行周期（如：2025-11-01 ~ 2025-11-07）'),
    sa.Column('mode', sa.String(length=30), nullable=False, comment='出行方式（walk/bike/public_transit/car）'),
    sa.Column('distance', sa.Float(), nullable=False, comment='出行里程（公里）'),
    sa.Column('note', sa.Text(), nullable=True, comment='出行备注（可选）'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='记录创建时间'),
    sa.ForeignKeyConstraint(['username'], ['tb_user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_usertrip')
    # ### end Alembic commands ###
