"""empty message

Revision ID: e6f7e6e7f9ec
Revises: bdfab6da94c4
Create Date: 2025-12-11 17:04:06.112579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6f7e6e7f9ec'
down_revision = 'bdfab6da94c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_merchant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('now_points', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('all_points', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('use_points', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_merchant', schema=None) as batch_op:
        batch_op.drop_column('use_points')
        batch_op.drop_column('all_points')
        batch_op.drop_column('now_points')

    # ### end Alembic commands ###
