"""empty message

Revision ID: e7651cdb7b29
Revises: 29811b201966
Create Date: 2025-12-10 19:03:21.825674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7651cdb7b29'
down_revision = '29811b201966'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_usertrip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, comment='审核状态：pending-审核中，approved-通过，rejected-驳回'))
        batch_op.add_column(sa.Column('audit_time', sa.DateTime(), nullable=True, comment='审核完成时间'))
        batch_op.add_column(sa.Column('audit_admin', sa.String(length=50), nullable=True, comment='审核管理员用户名'))
        batch_op.add_column(sa.Column('reject_reason', sa.String(length=200), nullable=True, comment='驳回原因（可选）'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_usertrip', schema=None) as batch_op:
        batch_op.drop_column('reject_reason')
        batch_op.drop_column('audit_admin')
        batch_op.drop_column('audit_time')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
