"""empty message

Revision ID: f0cb7040480a
Revises: 5d7f008d15c0
Create Date: 2025-12-07 20:14:17.551639

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f0cb7040480a'
down_revision = '5d7f008d15c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('now_points', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('all_points', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('use_points', sa.Integer(), nullable=True))
        batch_op.drop_column('points')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('use_points')
        batch_op.drop_column('all_points')
        batch_op.drop_column('now_points')

    # ### end Alembic commands ###
